# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sid_query.protos.sid_query import sid_query_pb2 as sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sid_query/protos/sid_query/sid_query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeakerRegistryServiceStub(object):
    """//////////////////////////////////////////////////////////
    实体管理服务（增 / 改 / 删 / 查）
    //////////////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEntity = channel.unary_unary(
                '/speaker.query.v1.SpeakerRegistryService/RegisterEntity',
                request_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.RegisterEntityRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.RegisterEntityResponse.FromString,
                _registered_method=True)
        self.UpdateEntity = channel.unary_unary(
                '/speaker.query.v1.SpeakerRegistryService/UpdateEntity',
                request_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.UpdateEntityRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.UpdateEntityResponse.FromString,
                _registered_method=True)
        self.DeleteEntity = channel.unary_unary(
                '/speaker.query.v1.SpeakerRegistryService/DeleteEntity',
                request_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.DeleteEntityRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.DeleteEntityResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/speaker.query.v1.SpeakerRegistryService/GetEntity',
                request_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.GetEntityRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.GetEntityResponse.FromString,
                _registered_method=True)


class SpeakerRegistryServiceServicer(object):
    """//////////////////////////////////////////////////////////
    实体管理服务（增 / 改 / 删 / 查）
    //////////////////////////////////////////////////////////

    """

    def RegisterEntity(self, request, context):
        """注册新实体（通过音频）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntity(self, request, context):
        """更新已有实体（追加或覆盖特征）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntity(self, request, context):
        """删除实体
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """获取实体基础信息（不做相似度检索）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakerRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEntity,
                    request_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.RegisterEntityRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.RegisterEntityResponse.SerializeToString,
            ),
            'UpdateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntity,
                    request_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.UpdateEntityRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.UpdateEntityResponse.SerializeToString,
            ),
            'DeleteEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntity,
                    request_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.DeleteEntityRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.DeleteEntityResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.GetEntityRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.GetEntityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speaker.query.v1.SpeakerRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speaker.query.v1.SpeakerRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeakerRegistryService(object):
    """//////////////////////////////////////////////////////////
    实体管理服务（增 / 改 / 删 / 查）
    //////////////////////////////////////////////////////////

    """

    @staticmethod
    def RegisterEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speaker.query.v1.SpeakerRegistryService/RegisterEntity',
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.RegisterEntityRequest.SerializeToString,
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.RegisterEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speaker.query.v1.SpeakerRegistryService/UpdateEntity',
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.UpdateEntityRequest.SerializeToString,
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.UpdateEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speaker.query.v1.SpeakerRegistryService/DeleteEntity',
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.DeleteEntityRequest.SerializeToString,
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.DeleteEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speaker.query.v1.SpeakerRegistryService/GetEntity',
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.GetEntityRequest.SerializeToString,
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.GetEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeakerQueryServiceStub(object):
    """//////////////////////////////////////////////////////////
    查询服务（在线推理）
    //////////////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuerySpeaker = channel.unary_unary(
                '/speaker.query.v1.SpeakerQueryService/QuerySpeaker',
                request_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.QuerySpeakerRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.QuerySpeakerResponse.FromString,
                _registered_method=True)


class SpeakerQueryServiceServicer(object):
    """//////////////////////////////////////////////////////////
    查询服务（在线推理）
    //////////////////////////////////////////////////////////

    """

    def QuerySpeaker(self, request, context):
        """输入一段音频，返回可能的说话人 / 设备 / 实体
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeakerQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuerySpeaker': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySpeaker,
                    request_deserializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.QuerySpeakerRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.QuerySpeakerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speaker.query.v1.SpeakerQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speaker.query.v1.SpeakerQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeakerQueryService(object):
    """//////////////////////////////////////////////////////////
    查询服务（在线推理）
    //////////////////////////////////////////////////////////

    """

    @staticmethod
    def QuerySpeaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speaker.query.v1.SpeakerQueryService/QuerySpeaker',
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.QuerySpeakerRequest.SerializeToString,
            sid__query_dot_protos_dot_sid__query_dot_sid__query__pb2.QuerySpeakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
