"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EntityInfo(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    对外实体信息（业务真正关心的对象）
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ENTITY_ID_FIELD_NUMBER: builtins.int
    ENTITY_TYPE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    entity_id: builtins.str
    """实体唯一标识"""
    entity_type: builtins.str
    """实体类型，如 person / device / account"""
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """业务自定义信息"""

    def __init__(
        self,
        *,
        entity_id: builtins.str = ...,
        entity_type: builtins.str = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity_id", b"entity_id", "entity_type", b"entity_type", "metadata", b"metadata"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EntityInfo: typing_extensions.TypeAlias = EntityInfo

@typing.final
class AudioFormat(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    音频输入描述
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    CHANNELS_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    sample_rate: builtins.int
    """采样率，如 16000"""
    channels: builtins.int
    """声道数，如 1"""
    encoding: builtins.str
    """编码格式，如 pcm16 / wav / flac"""
    def __init__(
        self,
        *,
        sample_rate: builtins.int = ...,
        channels: builtins.int = ...,
        encoding: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["channels", b"channels", "encoding", b"encoding", "sample_rate", b"sample_rate"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AudioFormat: typing_extensions.TypeAlias = AudioFormat

@typing.final
class QueryConfig(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    查询配置（控制返回行为）
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOP_K_FIELD_NUMBER: builtins.int
    SCORE_THRESHOLD_FIELD_NUMBER: builtins.int
    RETURN_SCORE_FIELD_NUMBER: builtins.int
    top_k: builtins.int
    """最多返回多少个候选实体
    top_k = 1 表示“直接告诉我是谁”
    """
    score_threshold: builtins.float
    """相似度阈值，低于该值的不返回
    0 表示不启用
    """
    return_score: builtins.bool
    """是否在返回中包含匹配分数"""
    def __init__(
        self,
        *,
        top_k: builtins.int = ...,
        score_threshold: builtins.float = ...,
        return_score: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["return_score", b"return_score", "score_threshold", b"score_threshold", "top_k", b"top_k"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryConfig: typing_extensions.TypeAlias = QueryConfig

@typing.final
class QuerySpeakerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUDIO_FIELD_NUMBER: builtins.int
    AUDIO_FORMAT_FIELD_NUMBER: builtins.int
    QUERY_CONFIG_FIELD_NUMBER: builtins.int
    audio: builtins.bytes
    """原始音频数据"""
    @property
    def audio_format(self) -> Global___AudioFormat:
        """音频格式"""

    @property
    def query_config(self) -> Global___QueryConfig:
        """查询行为配置"""

    def __init__(
        self,
        *,
        audio: builtins.bytes = ...,
        audio_format: Global___AudioFormat | None = ...,
        query_config: Global___QueryConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["audio_format", b"audio_format", "query_config", b"query_config"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["audio", b"audio", "audio_format", b"audio_format", "query_config", b"query_config"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QuerySpeakerRequest: typing_extensions.TypeAlias = QuerySpeakerRequest

@typing.final
class MatchEntity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    score: builtins.float
    """匹配分数（仅在 return_score = true 时有意义）"""
    @property
    def entity(self) -> Global___EntityInfo:
        """命中的实体信息"""

    def __init__(
        self,
        *,
        entity: Global___EntityInfo | None = ...,
        score: builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity", b"entity"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity", b"entity", "score", b"score"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MatchEntity: typing_extensions.TypeAlias = MatchEntity

@typing.final
class QuerySpeakerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MATCHES_FIELD_NUMBER: builtins.int
    @property
    def matches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___MatchEntity]:
        """匹配到的实体列表"""

    def __init__(
        self,
        *,
        matches: collections.abc.Iterable[Global___MatchEntity] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["matches", b"matches"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QuerySpeakerResponse: typing_extensions.TypeAlias = QuerySpeakerResponse

@typing.final
class RegisterEntityRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    注册实体
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    AUDIO_FIELD_NUMBER: builtins.int
    AUDIO_FORMAT_FIELD_NUMBER: builtins.int
    audio: builtins.bytes
    """注册用音频数据"""
    @property
    def entity(self) -> Global___EntityInfo:
        """实体信息（entity_id 可由调用方指定，或由服务端生成）"""

    @property
    def audio_format(self) -> Global___AudioFormat:
        """音频格式"""

    def __init__(
        self,
        *,
        entity: Global___EntityInfo | None = ...,
        audio: builtins.bytes = ...,
        audio_format: Global___AudioFormat | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["audio_format", b"audio_format", "entity", b"entity"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["audio", b"audio", "audio_format", b"audio_format", "entity", b"entity"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RegisterEntityRequest: typing_extensions.TypeAlias = RegisterEntityRequest

@typing.final
class RegisterEntityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_ID_FIELD_NUMBER: builtins.int
    entity_id: builtins.str
    """最终使用的实体 ID"""
    def __init__(
        self,
        *,
        entity_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity_id", b"entity_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RegisterEntityResponse: typing_extensions.TypeAlias = RegisterEntityResponse

@typing.final
class UpdateEntityRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    更新实体
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["key", b"key", "value", b"value"]
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ENTITY_ID_FIELD_NUMBER: builtins.int
    AUDIO_FIELD_NUMBER: builtins.int
    AUDIO_FORMAT_FIELD_NUMBER: builtins.int
    OVERWRITE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    entity_id: builtins.str
    """要更新的实体 ID"""
    audio: builtins.bytes
    """新增或替换用的音频数据"""
    overwrite: builtins.bool
    """是否覆盖已有特征
    false：追加特征
    true ：重建该实体的特征
    """
    @property
    def audio_format(self) -> Global___AudioFormat:
        """音频格式"""

    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """可选：更新 metadata"""

    def __init__(
        self,
        *,
        entity_id: builtins.str = ...,
        audio: builtins.bytes = ...,
        audio_format: Global___AudioFormat | None = ...,
        overwrite: builtins.bool = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["audio_format", b"audio_format"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["audio", b"audio", "audio_format", b"audio_format", "entity_id", b"entity_id", "metadata", b"metadata", "overwrite", b"overwrite"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateEntityRequest: typing_extensions.TypeAlias = UpdateEntityRequest

@typing.final
class UpdateEntityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_ID_FIELD_NUMBER: builtins.int
    entity_id: builtins.str
    def __init__(
        self,
        *,
        entity_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity_id", b"entity_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateEntityResponse: typing_extensions.TypeAlias = UpdateEntityResponse

@typing.final
class DeleteEntityRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    删除实体
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_ID_FIELD_NUMBER: builtins.int
    entity_id: builtins.str
    def __init__(
        self,
        *,
        entity_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity_id", b"entity_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteEntityRequest: typing_extensions.TypeAlias = DeleteEntityRequest

@typing.final
class DeleteEntityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["success", b"success"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteEntityResponse: typing_extensions.TypeAlias = DeleteEntityResponse

@typing.final
class GetEntityRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////
    获取实体信息
    //////////////////////////////////////////////////////////
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_ID_FIELD_NUMBER: builtins.int
    entity_id: builtins.str
    def __init__(
        self,
        *,
        entity_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity_id", b"entity_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetEntityRequest: typing_extensions.TypeAlias = GetEntityRequest

@typing.final
class GetEntityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    @property
    def entity(self) -> Global___EntityInfo: ...
    def __init__(
        self,
        *,
        entity: Global___EntityInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity", b"entity"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["entity", b"entity"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetEntityResponse: typing_extensions.TypeAlias = GetEntityResponse
