"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import sid_query.protos.sid_query.sid_query_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SpeakerRegistryServiceStub:
    """//////////////////////////////////////////////////////////
    实体管理服务（增 / 改 / 删 / 查）
    //////////////////////////////////////////////////////////
    """

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> SpeakerRegistryServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> SpeakerRegistryServiceAsyncStub: ...
    RegisterEntity: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.RegisterEntityRequest, sid_query.protos.sid_query.sid_query_pb2.RegisterEntityResponse]
    """注册新实体（通过音频）"""
    UpdateEntity: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.UpdateEntityRequest, sid_query.protos.sid_query.sid_query_pb2.UpdateEntityResponse]
    """更新已有实体（追加或覆盖特征）"""
    DeleteEntity: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.DeleteEntityRequest, sid_query.protos.sid_query.sid_query_pb2.DeleteEntityResponse]
    """删除实体"""
    GetEntity: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.GetEntityRequest, sid_query.protos.sid_query.sid_query_pb2.GetEntityResponse]
    """获取实体基础信息（不做相似度检索）"""

@typing.type_check_only
class SpeakerRegistryServiceAsyncStub(SpeakerRegistryServiceStub):
    """//////////////////////////////////////////////////////////
    实体管理服务（增 / 改 / 删 / 查）
    //////////////////////////////////////////////////////////
    """

    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    RegisterEntity: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.RegisterEntityRequest, sid_query.protos.sid_query.sid_query_pb2.RegisterEntityResponse]  # type: ignore[assignment]
    """注册新实体（通过音频）"""
    UpdateEntity: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.UpdateEntityRequest, sid_query.protos.sid_query.sid_query_pb2.UpdateEntityResponse]  # type: ignore[assignment]
    """更新已有实体（追加或覆盖特征）"""
    DeleteEntity: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.DeleteEntityRequest, sid_query.protos.sid_query.sid_query_pb2.DeleteEntityResponse]  # type: ignore[assignment]
    """删除实体"""
    GetEntity: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.GetEntityRequest, sid_query.protos.sid_query.sid_query_pb2.GetEntityResponse]  # type: ignore[assignment]
    """获取实体基础信息（不做相似度检索）"""

class SpeakerRegistryServiceServicer(metaclass=abc.ABCMeta):
    """//////////////////////////////////////////////////////////
    实体管理服务（增 / 改 / 删 / 查）
    //////////////////////////////////////////////////////////
    """

    @abc.abstractmethod
    def RegisterEntity(
        self,
        request: sid_query.protos.sid_query.sid_query_pb2.RegisterEntityRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid_query.sid_query_pb2.RegisterEntityResponse, collections.abc.Awaitable[sid_query.protos.sid_query.sid_query_pb2.RegisterEntityResponse]]:
        """注册新实体（通过音频）"""

    @abc.abstractmethod
    def UpdateEntity(
        self,
        request: sid_query.protos.sid_query.sid_query_pb2.UpdateEntityRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid_query.sid_query_pb2.UpdateEntityResponse, collections.abc.Awaitable[sid_query.protos.sid_query.sid_query_pb2.UpdateEntityResponse]]:
        """更新已有实体（追加或覆盖特征）"""

    @abc.abstractmethod
    def DeleteEntity(
        self,
        request: sid_query.protos.sid_query.sid_query_pb2.DeleteEntityRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid_query.sid_query_pb2.DeleteEntityResponse, collections.abc.Awaitable[sid_query.protos.sid_query.sid_query_pb2.DeleteEntityResponse]]:
        """删除实体"""

    @abc.abstractmethod
    def GetEntity(
        self,
        request: sid_query.protos.sid_query.sid_query_pb2.GetEntityRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid_query.sid_query_pb2.GetEntityResponse, collections.abc.Awaitable[sid_query.protos.sid_query.sid_query_pb2.GetEntityResponse]]:
        """获取实体基础信息（不做相似度检索）"""

def add_SpeakerRegistryServiceServicer_to_server(servicer: SpeakerRegistryServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

class SpeakerQueryServiceStub:
    """//////////////////////////////////////////////////////////
    查询服务（在线推理）
    //////////////////////////////////////////////////////////
    """

    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> SpeakerQueryServiceStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> SpeakerQueryServiceAsyncStub: ...
    QuerySpeaker: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerRequest, sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerResponse]
    """输入一段音频，返回可能的说话人 / 设备 / 实体"""

@typing.type_check_only
class SpeakerQueryServiceAsyncStub(SpeakerQueryServiceStub):
    """//////////////////////////////////////////////////////////
    查询服务（在线推理）
    //////////////////////////////////////////////////////////
    """

    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    QuerySpeaker: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerRequest, sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerResponse]  # type: ignore[assignment]
    """输入一段音频，返回可能的说话人 / 设备 / 实体"""

class SpeakerQueryServiceServicer(metaclass=abc.ABCMeta):
    """//////////////////////////////////////////////////////////
    查询服务（在线推理）
    //////////////////////////////////////////////////////////
    """

    @abc.abstractmethod
    def QuerySpeaker(
        self,
        request: sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerResponse, collections.abc.Awaitable[sid_query.protos.sid_query.sid_query_pb2.QuerySpeakerResponse]]:
        """输入一段音频，返回可能的说话人 / 设备 / 实体"""

def add_SpeakerQueryServiceServicer_to_server(servicer: SpeakerQueryServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
