"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ClusterModel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ClusterModelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ClusterModel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ClusterByNum: _ClusterModel.ValueType  # 0
    ClusterByThreshold: _ClusterModel.ValueType  # 1

class ClusterModel(_ClusterModel, metaclass=_ClusterModelEnumTypeWrapper): ...

ClusterByNum: ClusterModel.ValueType  # 0
ClusterByThreshold: ClusterModel.ValueType  # 1
Global___ClusterModel: typing_extensions.TypeAlias = ClusterModel

@typing.final
class EngineInfoReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENGINELIST_FIELD_NUMBER: builtins.int
    VADLIST_FIELD_NUMBER: builtins.int
    LIDLIST_FIELD_NUMBER: builtins.int
    GIDLIST_FIELD_NUMBER: builtins.int
    @property
    def engineList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def vadList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def lidList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def gidList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        engineList: collections.abc.Iterable[builtins.str] | None = ...,
        vadList: collections.abc.Iterable[builtins.str] | None = ...,
        lidList: collections.abc.Iterable[builtins.str] | None = ...,
        gidList: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["engineList", b"engineList", "gidList", b"gidList", "lidList", b"lidList", "vadList", b"vadList"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EngineInfoReply: typing_extensions.TypeAlias = EngineInfoReply

@typing.final
class VadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    PCM_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    pcm: builtins.bytes
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        pcm: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["pcm", b"pcm", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VadRequest: typing_extensions.TypeAlias = VadRequest

@typing.final
class VadWavRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    FILEPATH_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    filePath: builtins.str
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        filePath: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["filePath", b"filePath", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VadWavRequest: typing_extensions.TypeAlias = VadWavRequest

@typing.final
class VadReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESEGLIST_FIELD_NUMBER: builtins.int
    @property
    def timeSegList(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TimeSeg]: ...
    def __init__(
        self,
        *,
        timeSegList: collections.abc.Iterable[Global___TimeSeg] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["timeSegList", b"timeSegList"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VadReply: typing_extensions.TypeAlias = VadReply

@typing.final
class TimeSeg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    start: builtins.int
    end: builtins.int
    def __init__(
        self,
        *,
        start: builtins.int = ...,
        end: builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["end", b"end", "start", b"start"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TimeSeg: typing_extensions.TypeAlias = TimeSeg

@typing.final
class FeatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    SIDALG_FIELD_NUMBER: builtins.int
    PCM_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    sidAlg: builtins.str
    pcm: builtins.bytes
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        sidAlg: builtins.str = ...,
        pcm: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["pcm", b"pcm", "sidAlg", b"sidAlg", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeatRequest: typing_extensions.TypeAlias = FeatRequest

@typing.final
class FeatWavRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    SIDALG_FIELD_NUMBER: builtins.int
    FILEPATHS_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    sidAlg: builtins.str
    @property
    def filePaths(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        sidAlg: builtins.str = ...,
        filePaths: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["filePaths", b"filePaths", "sidAlg", b"sidAlg", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeatWavRequest: typing_extensions.TypeAlias = FeatWavRequest

@typing.final
class FeatReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEAT_FIELD_NUMBER: builtins.int
    feat: builtins.bytes
    def __init__(
        self,
        *,
        feat: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["feat", b"feat"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeatReply: typing_extensions.TypeAlias = FeatReply

@typing.final
class TrainWavRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    SIDALG_FIELD_NUMBER: builtins.int
    FILEPATHS_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    sidAlg: builtins.str
    @property
    def filePaths(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        sidAlg: builtins.str = ...,
        filePaths: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["filePaths", b"filePaths", "sidAlg", b"sidAlg", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrainWavRequest: typing_extensions.TypeAlias = TrainWavRequest

@typing.final
class TrainRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    SIDALG_FIELD_NUMBER: builtins.int
    PCM_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    sidAlg: builtins.str
    @property
    def pcm(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        sidAlg: builtins.str = ...,
        pcm: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["pcm", b"pcm", "sidAlg", b"sidAlg", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrainRequest: typing_extensions.TypeAlias = TrainRequest

@typing.final
class TrainReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_FIELD_NUMBER: builtins.int
    model: builtins.bytes
    def __init__(
        self,
        *,
        model: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["model", b"model"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrainReply: typing_extensions.TypeAlias = TrainReply

@typing.final
class CompareRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIDALG_FIELD_NUMBER: builtins.int
    FEAT_FIELD_NUMBER: builtins.int
    MODELS_FIELD_NUMBER: builtins.int
    sidAlg: builtins.str
    feat: builtins.bytes
    @property
    def models(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        sidAlg: builtins.str = ...,
        feat: builtins.bytes = ...,
        models: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["feat", b"feat", "models", b"models", "sidAlg", b"sidAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompareRequest: typing_extensions.TypeAlias = CompareRequest

@typing.final
class CompareWavRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    SIDALG_FIELD_NUMBER: builtins.int
    FEATWAVLIST_FIELD_NUMBER: builtins.int
    MODELWAVLIST_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    sidAlg: builtins.str
    @property
    def featWavList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def modelWavList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        sidAlg: builtins.str = ...,
        featWavList: collections.abc.Iterable[builtins.str] | None = ...,
        modelWavList: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["featWavList", b"featWavList", "modelWavList", b"modelWavList", "sidAlg", b"sidAlg", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompareWavRequest: typing_extensions.TypeAlias = CompareWavRequest

@typing.final
class CompareReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCORELIST_FIELD_NUMBER: builtins.int
    @property
    def ScoreList(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ScoreInfo]: ...
    def __init__(
        self,
        *,
        ScoreList: collections.abc.Iterable[Global___ScoreInfo] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["ScoreList", b"ScoreList"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompareReply: typing_extensions.TypeAlias = CompareReply

@typing.final
class ScoreInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCORE_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    score: builtins.float
    err: builtins.str
    def __init__(
        self,
        *,
        score: builtins.float = ...,
        err: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["err", b"err", "score", b"score"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScoreInfo: typing_extensions.TypeAlias = ScoreInfo

@typing.final
class ClusterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    SIDALG_FIELD_NUMBER: builtins.int
    PCM_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    NUMCLUSTER_FIELD_NUMBER: builtins.int
    THRESHOLD_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    sidAlg: builtins.str
    model: Global___ClusterModel.ValueType
    numCluster: builtins.int
    threshold: builtins.float
    @property
    def pcm(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        sidAlg: builtins.str = ...,
        pcm: collections.abc.Iterable[builtins.bytes] | None = ...,
        model: Global___ClusterModel.ValueType = ...,
        numCluster: builtins.int = ...,
        threshold: builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["model", b"model", "numCluster", b"numCluster", "pcm", b"pcm", "sidAlg", b"sidAlg", "threshold", b"threshold", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ClusterRequest: typing_extensions.TypeAlias = ClusterRequest

@typing.final
class ClusterReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["result", b"result"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ClusterReply: typing_extensions.TypeAlias = ClusterReply

@typing.final
class ExtendedRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VADALG_FIELD_NUMBER: builtins.int
    LIDALG_FIELD_NUMBER: builtins.int
    GIDALG_FIELD_NUMBER: builtins.int
    PCM_FIELD_NUMBER: builtins.int
    vadAlg: builtins.str
    lidAlg: builtins.str
    gidAlg: builtins.str
    pcm: builtins.bytes
    def __init__(
        self,
        *,
        vadAlg: builtins.str = ...,
        lidAlg: builtins.str = ...,
        gidAlg: builtins.str = ...,
        pcm: builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["gidAlg", b"gidAlg", "lidAlg", b"lidAlg", "pcm", b"pcm", "vadAlg", b"vadAlg"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExtendedRequest: typing_extensions.TypeAlias = ExtendedRequest

@typing.final
class ExtendedReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIST_FIELD_NUMBER: builtins.int
    @property
    def list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ExtendedInfo]: ...
    def __init__(
        self,
        *,
        list: collections.abc.Iterable[Global___ExtendedInfo] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["list", b"list"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExtendedReply: typing_extensions.TypeAlias = ExtendedReply

@typing.final
class ExtendedInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCORE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    ALG_FIELD_NUMBER: builtins.int
    score: builtins.float
    value: builtins.str
    alg: builtins.str
    def __init__(
        self,
        *,
        score: builtins.float = ...,
        value: builtins.str = ...,
        alg: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["alg", b"alg", "score", b"score", "value", b"value"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExtendedInfo: typing_extensions.TypeAlias = ExtendedInfo
