"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import google.protobuf.empty_pb2
import grpc
import grpc.aio
import sid_query.protos.sid.sid_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EngineStub:
    @typing.overload
    def __new__(cls, channel: grpc.Channel) -> EngineStub: ...
    @typing.overload
    def __new__(cls, channel: grpc.aio.Channel) -> EngineAsyncStub: ...
    EngineInfo: grpc.UnaryUnaryMultiCallable[google.protobuf.empty_pb2.Empty, sid_query.protos.sid.sid_pb2.EngineInfoReply]
    Vad: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.VadRequest, sid_query.protos.sid.sid_pb2.VadReply]
    VadWav: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.VadWavRequest, sid_query.protos.sid.sid_pb2.VadReply]
    Feature: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.FeatRequest, sid_query.protos.sid.sid_pb2.FeatReply]
    FeatureWav: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.FeatWavRequest, sid_query.protos.sid.sid_pb2.FeatReply]
    Train: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.TrainRequest, sid_query.protos.sid.sid_pb2.TrainReply]
    TrainWav: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.TrainWavRequest, sid_query.protos.sid.sid_pb2.TrainReply]
    Compare: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.CompareRequest, sid_query.protos.sid.sid_pb2.CompareReply]
    CompareWav: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.CompareWavRequest, sid_query.protos.sid.sid_pb2.CompareReply]
    Cluster: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.ClusterRequest, sid_query.protos.sid.sid_pb2.ClusterReply]
    Extended: grpc.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.ExtendedRequest, sid_query.protos.sid.sid_pb2.ExtendedReply]

@typing.type_check_only
class EngineAsyncStub(EngineStub):
    def __init__(self, channel: grpc.aio.Channel) -> None: ...
    EngineInfo: grpc.aio.UnaryUnaryMultiCallable[google.protobuf.empty_pb2.Empty, sid_query.protos.sid.sid_pb2.EngineInfoReply]  # type: ignore[assignment]
    Vad: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.VadRequest, sid_query.protos.sid.sid_pb2.VadReply]  # type: ignore[assignment]
    VadWav: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.VadWavRequest, sid_query.protos.sid.sid_pb2.VadReply]  # type: ignore[assignment]
    Feature: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.FeatRequest, sid_query.protos.sid.sid_pb2.FeatReply]  # type: ignore[assignment]
    FeatureWav: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.FeatWavRequest, sid_query.protos.sid.sid_pb2.FeatReply]  # type: ignore[assignment]
    Train: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.TrainRequest, sid_query.protos.sid.sid_pb2.TrainReply]  # type: ignore[assignment]
    TrainWav: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.TrainWavRequest, sid_query.protos.sid.sid_pb2.TrainReply]  # type: ignore[assignment]
    Compare: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.CompareRequest, sid_query.protos.sid.sid_pb2.CompareReply]  # type: ignore[assignment]
    CompareWav: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.CompareWavRequest, sid_query.protos.sid.sid_pb2.CompareReply]  # type: ignore[assignment]
    Cluster: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.ClusterRequest, sid_query.protos.sid.sid_pb2.ClusterReply]  # type: ignore[assignment]
    Extended: grpc.aio.UnaryUnaryMultiCallable[sid_query.protos.sid.sid_pb2.ExtendedRequest, sid_query.protos.sid.sid_pb2.ExtendedReply]  # type: ignore[assignment]

class EngineServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def EngineInfo(
        self,
        request: google.protobuf.empty_pb2.Empty,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.EngineInfoReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.EngineInfoReply]]: ...

    @abc.abstractmethod
    def Vad(
        self,
        request: sid_query.protos.sid.sid_pb2.VadRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.VadReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.VadReply]]: ...

    @abc.abstractmethod
    def VadWav(
        self,
        request: sid_query.protos.sid.sid_pb2.VadWavRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.VadReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.VadReply]]: ...

    @abc.abstractmethod
    def Feature(
        self,
        request: sid_query.protos.sid.sid_pb2.FeatRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.FeatReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.FeatReply]]: ...

    @abc.abstractmethod
    def FeatureWav(
        self,
        request: sid_query.protos.sid.sid_pb2.FeatWavRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.FeatReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.FeatReply]]: ...

    @abc.abstractmethod
    def Train(
        self,
        request: sid_query.protos.sid.sid_pb2.TrainRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.TrainReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.TrainReply]]: ...

    @abc.abstractmethod
    def TrainWav(
        self,
        request: sid_query.protos.sid.sid_pb2.TrainWavRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.TrainReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.TrainReply]]: ...

    @abc.abstractmethod
    def Compare(
        self,
        request: sid_query.protos.sid.sid_pb2.CompareRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.CompareReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.CompareReply]]: ...

    @abc.abstractmethod
    def CompareWav(
        self,
        request: sid_query.protos.sid.sid_pb2.CompareWavRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.CompareReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.CompareReply]]: ...

    @abc.abstractmethod
    def Cluster(
        self,
        request: sid_query.protos.sid.sid_pb2.ClusterRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.ClusterReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.ClusterReply]]: ...

    @abc.abstractmethod
    def Extended(
        self,
        request: sid_query.protos.sid.sid_pb2.ExtendedRequest,
        context: _ServicerContext,
    ) -> typing.Union[sid_query.protos.sid.sid_pb2.ExtendedReply, collections.abc.Awaitable[sid_query.protos.sid.sid_pb2.ExtendedReply]]: ...

def add_EngineServicer_to_server(servicer: EngineServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
