# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sid_query.protos.sid import sid_pb2 as sid__query_dot_protos_dot_sid_dot_sid__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sid_query/protos/sid/sid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EngineInfo = channel.unary_unary(
                '/pb.Engine/EngineInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.EngineInfoReply.FromString,
                _registered_method=True)
        self.Vad = channel.unary_unary(
                '/pb.Engine/Vad',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadReply.FromString,
                _registered_method=True)
        self.VadWav = channel.unary_unary(
                '/pb.Engine/VadWav',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadWavRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadReply.FromString,
                _registered_method=True)
        self.Feature = channel.unary_unary(
                '/pb.Engine/Feature',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatReply.FromString,
                _registered_method=True)
        self.FeatureWav = channel.unary_unary(
                '/pb.Engine/FeatureWav',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatWavRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatReply.FromString,
                _registered_method=True)
        self.Train = channel.unary_unary(
                '/pb.Engine/Train',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainReply.FromString,
                _registered_method=True)
        self.TrainWav = channel.unary_unary(
                '/pb.Engine/TrainWav',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainWavRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainReply.FromString,
                _registered_method=True)
        self.Compare = channel.unary_unary(
                '/pb.Engine/Compare',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareReply.FromString,
                _registered_method=True)
        self.CompareWav = channel.unary_unary(
                '/pb.Engine/CompareWav',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareWavRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareReply.FromString,
                _registered_method=True)
        self.Cluster = channel.unary_unary(
                '/pb.Engine/Cluster',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ClusterRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ClusterReply.FromString,
                _registered_method=True)
        self.Extended = channel.unary_unary(
                '/pb.Engine/Extended',
                request_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ExtendedRequest.SerializeToString,
                response_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ExtendedReply.FromString,
                _registered_method=True)


class EngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EngineInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Vad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VadWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Feature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FeatureWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Extended(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EngineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.EngineInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.EngineInfoReply.SerializeToString,
            ),
            'Vad': grpc.unary_unary_rpc_method_handler(
                    servicer.Vad,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadReply.SerializeToString,
            ),
            'VadWav': grpc.unary_unary_rpc_method_handler(
                    servicer.VadWav,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadWavRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.VadReply.SerializeToString,
            ),
            'Feature': grpc.unary_unary_rpc_method_handler(
                    servicer.Feature,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatReply.SerializeToString,
            ),
            'FeatureWav': grpc.unary_unary_rpc_method_handler(
                    servicer.FeatureWav,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatWavRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatReply.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainReply.SerializeToString,
            ),
            'TrainWav': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainWav,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainWavRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainReply.SerializeToString,
            ),
            'Compare': grpc.unary_unary_rpc_method_handler(
                    servicer.Compare,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareReply.SerializeToString,
            ),
            'CompareWav': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareWav,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareWavRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareReply.SerializeToString,
            ),
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ClusterRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ClusterReply.SerializeToString,
            ),
            'Extended': grpc.unary_unary_rpc_method_handler(
                    servicer.Extended,
                    request_deserializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ExtendedRequest.FromString,
                    response_serializer=sid__query_dot_protos_dot_sid_dot_sid__pb2.ExtendedReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.Engine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EngineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/EngineInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.EngineInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Vad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/Vad',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.VadRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.VadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VadWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/VadWav',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.VadWavRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.VadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Feature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/Feature',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FeatureWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/FeatureWav',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatWavRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.FeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/Train',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/TrainWav',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainWavRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.TrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/Compare',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/CompareWav',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareWavRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.CompareReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/Cluster',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.ClusterRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.ClusterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Extended(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.Engine/Extended',
            sid__query_dot_protos_dot_sid_dot_sid__pb2.ExtendedRequest.SerializeToString,
            sid__query_dot_protos_dot_sid_dot_sid__pb2.ExtendedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
